# [window]
# decorations = "none"
# opacity = 0.8
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[colors.primary]
background = "0x0f0f0f"
